from __future__ import annotations

from dataclasses import asdict
from typing import Any, Dict, Literal, Optional

import numpy as np
from scipy.optimize import linear_sum_assignment

from .config import SimConfig

PolicyName = Literal[
    "rssi",
    "hysteresis",
    "ttt_handover",
    "load_aware",
    "darc_no_obs",
    "darc",
    "robust_darc",
    "shield_darc",
    "stable_global",
    "stable_global_oracle",
    "stable_global_no_switch",
    "regime_orchestrator",
    "q_learning",
]

POLICY_NAMES = [
    "rssi",
    "hysteresis",
    "ttt_handover",
    "load_aware",
    "darc_no_obs",
    "darc",
    "robust_darc",
    "shield_darc",
    "stable_global",
    "regime_orchestrator",
    "q_learning",
]


def _reflect_positions(pos: np.ndarray, vel: np.ndarray, grid_size: float) -> np.ndarray:
    """Reflect positions at boundaries under constant-velocity prediction."""
    raw = pos + vel
    period = 2.0 * grid_size
    folded = np.mod(raw, period)
    return np.where(folded <= grid_size, folded, period - folded)


def generate_trace(cfg: SimConfig, seed: int | None = None, steps: int | None = None) -> Dict[str, np.ndarray]:
    """Generate an exogenous environment trace independent of controller randomness.

    The trace contains only quantities that could be observed/generated by the environment.
    Observer states are intentionally not stored so that every controller reconstructs them online.
    """
    rng = np.random.default_rng(cfg.seed if seed is None else seed)
    steps = int(steps or cfg.steps)

    pos = rng.uniform(0.12 * cfg.grid_size, 0.88 * cfg.grid_size, size=(cfg.n_users, 2))
    angles = rng.uniform(0, 2 * np.pi, size=cfg.n_users)
    speeds = rng.uniform(0.35, cfg.max_speed, size=cfg.n_users)
    vel = np.stack([np.cos(angles) * speeds, np.sin(angles) * speeds], axis=1)
    base_demand = rng.uniform(1.8, 5.0, size=cfg.n_users)
    disturbance = np.zeros(cfg.n_aps)
    global_burst = 0.0

    user_pos = np.zeros((steps, cfg.n_users, 2), dtype=float)
    user_vel = np.zeros((steps, cfg.n_users, 2), dtype=float)
    disturbance_hist = np.zeros((steps, cfg.n_aps), dtype=float)
    demand_hist = np.zeros((steps, cfg.n_users), dtype=float)
    burst_hist = np.zeros(steps, dtype=float)

    for t in range(steps):
        user_pos[t] = pos
        user_vel[t] = vel

        cyclic = 0.85 * np.sin(2 * np.pi * (t / 120.0) + np.arange(cfg.n_users) * 0.31)
        traffic_burst = 1.0 if (t // 90) % 2 == 1 else 0.0
        locality = 0.18 * np.cos(np.arange(cfg.n_users) * 0.7)
        demand_hist[t] = np.clip(base_demand + cyclic + traffic_burst + locality, 1.0, 7.0)

        if rng.random() < cfg.global_burst_prob:
            global_burst = rng.uniform(cfg.global_burst_scale_low, cfg.global_burst_scale_high) * rng.choice([-1.0, 1.0])
        global_burst *= cfg.global_burst_decay
        innovation = rng.normal(0.0, cfg.disturbance_sigma, size=cfg.n_aps)
        disturbance = cfg.disturbance_ar * disturbance + innovation + 0.08 * global_burst

        if rng.random() < cfg.local_burst_prob:
            j = int(rng.integers(cfg.n_aps))
            disturbance[j] += rng.uniform(cfg.local_burst_scale_low, cfg.local_burst_scale_high) * rng.choice([-1.0, 1.0])

        disturbance = np.clip(disturbance, -cfg.disturbance_clip, cfg.disturbance_clip)
        disturbance_hist[t] = disturbance
        burst_hist[t] = global_burst

        noise = rng.normal(0.0, cfg.noise_std, size=vel.shape)
        vel = vel + 0.09 * noise
        speed_now = np.linalg.norm(vel, axis=1, keepdims=True)
        vel = vel / np.maximum(speed_now, 1e-9) * np.minimum(speed_now, cfg.max_speed)
        pos = _reflect_positions(pos, vel * cfg.dt, cfg.grid_size)

    return {
        "user_pos": user_pos,
        "user_vel": user_vel,
        "disturbance": disturbance_hist,
        "demand": demand_hist,
        "global_burst": burst_hist,
    }


class DistMobSim:
    """Mobile-network simulator with deterministic replay and multiple association policies."""

    def __init__(self, cfg: SimConfig, trace_data: Optional[Dict[str, np.ndarray]] = None, policy_seed: int | None = None):
        self.cfg = cfg
        self.rng = np.random.default_rng(cfg.seed if policy_seed is None else policy_seed)
        self.trace_data = trace_data
        self.trace_step = 0

        self.ap_pos, self.ap_bias = self._build_ap_geometry(cfg.n_aps)
        self.user_pos = self.rng.uniform(0.12 * cfg.grid_size, 0.88 * cfg.grid_size, size=(cfg.n_users, 2))
        angles = self.rng.uniform(0, 2 * np.pi, size=cfg.n_users)
        speeds = self.rng.uniform(0.35, cfg.max_speed, size=cfg.n_users)
        self.user_vel = np.stack([np.cos(angles) * speeds, np.sin(angles) * speeds], axis=1)
        self.user_demand = self.rng.uniform(1.8, 5.0, size=cfg.n_users)
        self.user_assoc = self.rng.integers(0, cfg.n_aps, size=cfg.n_users)
        self.prev_assoc = self.user_assoc.copy()
        self.ttt_counter = np.zeros(cfg.n_users, dtype=int)
        self.ttt_target = self.user_assoc.copy()

        self.disturbance = np.zeros(cfg.n_aps)
        self.disturbance_prev = np.zeros(cfg.n_aps)
        self.disturbance_est = np.zeros(cfg.n_aps)
        self.disturbance_volatility = np.zeros(cfg.n_aps)
        self.global_burst = 0.0
        self.regime_mode_last = "darc"
        self.q_tables: list[dict[tuple[int, int, int, int, int], np.ndarray]] = [dict() for _ in range(cfg.n_users)]
        self._prediction_cache: dict[tuple[int, bool, int], np.ndarray] = {}

        if self.trace_data is not None:
            self._load_trace_step(0)

    def _build_ap_geometry(self, n_aps: int) -> tuple[np.ndarray, np.ndarray]:
        if n_aps <= 0:
            raise ValueError("n_aps must be positive")
        cfg = self.cfg
        margin = cfg.grid_size * 0.16
        cols = int(np.ceil(np.sqrt(n_aps)))
        rows = int(np.ceil(n_aps / cols))
        xs = np.linspace(margin, cfg.grid_size - margin, cols)
        ys = np.linspace(margin, cfg.grid_size - margin, rows)
        coords = np.array([(x, y) for y in ys for x in xs], dtype=float)[:n_aps]
        idx = np.arange(n_aps, dtype=float)
        bias = 0.5 * cfg.ap_bias_span * (n_aps - 1 - 2.0 * idx / max(n_aps - 1, 1))
        bias = bias - np.mean(bias)
        return coords, bias

    def metadata(self) -> Dict[str, Any]:
        return asdict(self.cfg)

    def _load_trace_step(self, t: int) -> None:
        if self.trace_data is None:
            return
        self.trace_step = int(t)
        self.user_pos = np.array(self.trace_data["user_pos"][t], dtype=float)
        self.user_vel = np.array(self.trace_data["user_vel"][t], dtype=float)
        self.disturbance = np.array(self.trace_data["disturbance"][t], dtype=float)
        self.user_demand = np.array(self.trace_data["demand"][t], dtype=float)
        self.global_burst = float(self.trace_data.get("global_burst", np.zeros(len(self.trace_data["demand"])))[t])

    def _observe_trace_disturbance(self, t: int) -> None:
        current = np.array(self.disturbance, dtype=float)
        if t == 0:
            self.disturbance_prev = np.zeros_like(current)
        else:
            self.disturbance_prev = np.array(self.trace_data["disturbance"][t - 1], dtype=float)
        self.disturbance_est = (1.0 - self.cfg.observer_alpha) * self.disturbance_est + self.cfg.observer_alpha * current
        delta = np.abs(current - self.disturbance_prev)
        self.disturbance_volatility = self.cfg.volatility_beta * self.disturbance_volatility + (1.0 - self.cfg.volatility_beta) * delta

    def _step_synthetic_environment(self) -> None:
        cfg = self.cfg
        self.disturbance_prev = self.disturbance.copy()
        if self.rng.random() < cfg.global_burst_prob:
            self.global_burst = self.rng.uniform(cfg.global_burst_scale_low, cfg.global_burst_scale_high) * self.rng.choice([-1.0, 1.0])
        self.global_burst *= cfg.global_burst_decay
        self.disturbance = cfg.disturbance_ar * self.disturbance + self.rng.normal(0, cfg.disturbance_sigma, size=cfg.n_aps) + 0.08 * self.global_burst
        if self.rng.random() < cfg.local_burst_prob:
            j = int(self.rng.integers(cfg.n_aps))
            self.disturbance[j] += self.rng.uniform(cfg.local_burst_scale_low, cfg.local_burst_scale_high) * self.rng.choice([-1.0, 1.0])
        self.disturbance = np.clip(self.disturbance, -cfg.disturbance_clip, cfg.disturbance_clip)
        self.disturbance_est = (1.0 - cfg.observer_alpha) * self.disturbance_est + cfg.observer_alpha * self.disturbance
        delta = np.abs(self.disturbance - self.disturbance_prev)
        self.disturbance_volatility = cfg.volatility_beta * self.disturbance_volatility + (1.0 - cfg.volatility_beta) * delta

        noise = self.rng.normal(0, cfg.noise_std, size=self.user_vel.shape)
        self.user_vel += 0.09 * noise
        speed_now = np.linalg.norm(self.user_vel, axis=1, keepdims=True)
        self.user_vel = self.user_vel / np.maximum(speed_now, 1e-9) * np.minimum(speed_now, cfg.max_speed)
        self.user_pos = _reflect_positions(self.user_pos, self.user_vel * cfg.dt, cfg.grid_size)

    def _rate_from_snr(self, snr_db: np.ndarray, load: int | np.ndarray) -> np.ndarray:
        cfg = self.cfg
        load_arr = np.asarray(load, dtype=float)
        eff_snr = snr_db - cfg.load_penalty_db * np.maximum(0.0, load_arr - 1.0)
        lin = 10.0 ** (eff_snr / 10.0)
        potential = np.clip(cfg.rate_scale * np.log2(1.0 + lin), 0.0, cfg.max_potential_rate)
        potential = potential / (1.0 + cfg.capacity_load_factor * np.maximum(0.0, load_arr - 1.0))
        return potential

    def _snr_for_state(self, user_pos: np.ndarray, disturbance: np.ndarray, counts: np.ndarray | None = None) -> np.ndarray:
        cfg = self.cfg
        pos = np.asarray(user_pos)
        if pos.ndim == 1:
            pos = pos[None, :]
        diff = pos[:, None, :] - self.ap_pos[None, :, :]
        distance = np.linalg.norm(diff, axis=2) + 1.0
        pathloss = 18.0 * np.log10(distance) * (cfg.pathloss_exp / 2.35)
        snr = cfg.base_snr_db - pathloss + self.ap_bias[None, :] - np.asarray(disturbance)[None, :]
        if counts is not None:
            snr = snr - cfg.load_penalty_db * np.maximum(0, np.asarray(counts, dtype=float)[None, :] - 1.0)
        return snr

    def link_score(self) -> np.ndarray:
        return self._snr_for_state(self.user_pos, self.disturbance)

    def demand_profile(self, t: int) -> np.ndarray:
        if self.trace_data is not None:
            return np.array(self.user_demand, dtype=float)
        cyclic = 0.85 * np.sin(2 * np.pi * (t / 120.0) + np.arange(self.cfg.n_users) * 0.31)
        traffic_burst = 1.0 if (t // 90) % 2 == 1 else 0.0
        locality = 0.18 * np.cos(np.arange(self.cfg.n_users) * 0.7)
        return np.clip(self.user_demand + cyclic + traffic_burst + locality, 1.0, 7.0)

    def evaluate_assignments(self, assoc: np.ndarray, demand: np.ndarray):
        assoc = np.asarray(assoc, dtype=int)
        demand = np.asarray(demand, dtype=float)
        counts = np.bincount(assoc, minlength=self.cfg.n_aps)
        snr = self.link_score()
        scores = np.zeros((self.cfg.n_users, self.cfg.n_aps), dtype=float)
        for j in range(self.cfg.n_aps):
            scores[:, j] = self._rate_from_snr(snr[:, j], int(counts[j]))

        throughput = np.zeros(self.cfg.n_users, dtype=float)
        for j in range(self.cfg.n_aps):
            idx = np.where(assoc == j)[0]
            if len(idx) == 0:
                continue
            pot = scores[idx, j]
            denom = float(np.sum(pot))
            if denom <= 1e-12:
                throughput[idx] = 0.0
            else:
                throughput[idx] = self.cfg.capacity_per_ap * pot / denom

        outage = throughput < demand
        return throughput, outage, scores, counts

    def _base_candidate(self, i: int, j: int, counts: np.ndarray | None = None, use_load: bool = True) -> float:
        c = np.zeros(self.cfg.n_aps, dtype=int) if counts is None else np.asarray(counts)
        snr = self._snr_for_state(self.user_pos[i], self.disturbance)[0, j]
        if use_load:
            snr -= self.cfg.load_penalty_db * max(0, int(c[j]) - 1)
        return float(snr)

    def _risk_vector(self, use_estimate: bool = True) -> np.ndarray:
        src = self.disturbance_est if use_estimate else self.disturbance
        return np.abs(src) + 0.7 * self.disturbance_volatility + 0.12 * abs(float(self.global_burst))

    def _predict_user_position(self, i: int, horizon: int) -> np.ndarray:
        cfg = self.cfg
        pos = self.user_pos[i].copy()
        vel_step = self.user_vel[i] * cfg.dt
        for _ in range(max(0, int(horizon))):
            pos = _reflect_positions(pos, vel_step, cfg.grid_size)
        return pos

    def _predict_disturbance(self, j: int, horizon: int, use_estimate: bool = True) -> float:
        cfg = self.cfg
        source = float(self.disturbance_est[j] if use_estimate else self.disturbance[j])
        burst = 0.08 * float(self.global_burst)
        rho = cfg.disturbance_ar
        h = max(1, int(horizon))
        return float(source * (rho ** h) + burst * (rho ** max(0, h - 1)))

    def _predicted_rate(self, i: int, j: int, nominal_load: int, horizon: int, use_estimate: bool) -> float:
        key = (int(horizon), bool(use_estimate), int(nominal_load))
        rates = self._prediction_cache.get(key)
        if rates is None:
            future_positions = np.stack([self._predict_user_position(u, horizon) for u in range(self.cfg.n_users)], axis=0)
            future_disturbances = np.array([self._predict_disturbance(ap, horizon, use_estimate=use_estimate) for ap in range(self.cfg.n_aps)])
            future_snr = self._snr_for_state(future_positions, future_disturbances)
            rates = self._rate_from_snr(future_snr, nominal_load)
            self._prediction_cache[key] = rates
        return float(rates[i, j])

    def _utility(self, i: int, j: int, counts: np.ndarray, demand_i: float, *, use_estimate: bool = True, robust: bool = False, safe: bool = False) -> float:
        cfg = self.cfg
        current = int(self.user_assoc[i])
        nominal_load = max(1, int(np.ceil(cfg.n_users / cfg.n_aps)))
        future_rate = self._predicted_rate(i, j, nominal_load, cfg.prediction_horizon + (2 if safe else 0), use_estimate)
        risk = abs(self._predict_disturbance(j, cfg.prediction_horizon, use_estimate)) + 0.7 * self.disturbance_volatility[j]
        switch_pen = cfg.handover_cost * cfg.switch_weight
        if j == current:
            switch_pen = 0.0
        elif robust:
            switch_pen *= 1.0
        elif safe:
            switch_pen *= cfg.safe_switch_scale

        speed_ratio = float(np.linalg.norm(self.user_vel[i]) / max(cfg.max_speed, 1e-9))
        dist_ratio = float(np.linalg.norm(self._predict_user_position(i, cfg.prediction_horizon) - self.ap_pos[j]) / max(cfg.grid_size, 1e-9))
        mobility_pen = cfg.robust_mobility_weight * speed_ratio * dist_ratio if robust or safe else 0.0
        uncertainty_pen = cfg.robust_uncertainty_weight * self.disturbance_volatility[j] if robust and not safe else 0.0
        if safe:
            uncertainty_pen = cfg.safe_uncertainty_weight * self.disturbance_volatility[j]
        inertia_pen = cfg.safe_inertia_weight * abs(float(self.global_burst)) if safe else 0.0

        shortfall = max(0.0, float(demand_i) - future_rate) / max(float(demand_i), 1e-9)
        return float(
            cfg.demand_weight * (future_rate / max(float(demand_i), 1e-9))
            - 1.5 * shortfall
            - cfg.disturbance_weight * risk
            - switch_pen
            - mobility_pen
            - uncertainty_pen
            - inertia_pen
        )

    def _select_regime_mode(self) -> str:
        risk = float(np.mean(self._risk_vector(use_estimate=True)))
        mobility = float(np.mean(np.linalg.norm(self.user_vel, axis=1)) / max(self.cfg.max_speed, 1e-9))
        base = self.cfg.regime_risk_scale * self.cfg.disturbance_sigma + self.cfg.regime_risk_offset
        low = base + self.cfg.regime_safe_margin
        high = base + self.cfg.regime_robust_margin
        h = self.cfg.regime_hysteresis
        last = self.regime_mode_last
        if last == "shield_darc":
            if risk > high - h:
                mode = "shield_darc"
            elif risk > low - h or mobility > self.cfg.regime_mobility_threshold:
                mode = "robust_darc"
            else:
                mode = "darc"
        elif last == "robust_darc":
            if risk > high:
                mode = "shield_darc"
            elif risk > low - h or mobility > self.cfg.regime_mobility_threshold + 0.05:
                mode = "robust_darc"
            else:
                mode = "darc"
        else:
            if risk > high:
                mode = "shield_darc"
            elif risk > low or mobility > self.cfg.regime_mobility_threshold:
                mode = "robust_darc"
            else:
                mode = "darc"
        self.regime_mode_last = mode
        return mode

    def _planner_snr_for_state(self, user_pos: np.ndarray, disturbance: np.ndarray) -> np.ndarray:
        """Planner-side proxy radio model; intentionally differs from evaluator truth."""
        cfg = self.cfg
        pos = np.asarray(user_pos)
        if pos.ndim == 1:
            pos = pos[None, :]
        diff = pos[:, None, :] - self.ap_pos[None, :, :]
        distance = np.linalg.norm(diff, axis=2) + 1.0
        pathloss = 18.0 * np.log10(distance) * (cfg.global_model_pathloss_exp / 2.35)
        return (
            cfg.base_snr_db
            - pathloss
            + self.ap_bias[None, :]
            + cfg.global_model_snr_bias_db
            - np.asarray(disturbance)[None, :]
        )

    def _planner_rate_from_snr(self, snr_db: np.ndarray, load: int | np.ndarray) -> np.ndarray:
        cfg = self.cfg
        load_arr = np.asarray(load, dtype=float)
        eff_snr = snr_db - cfg.load_penalty_db * np.maximum(0.0, load_arr - 1.0)
        lin = 10.0 ** (eff_snr / 10.0)
        potential = np.clip(
            cfg.global_model_rate_scale * np.log2(1.0 + lin),
            0.0,
            cfg.global_model_max_potential_rate,
        )
        return potential / (1.0 + cfg.global_model_capacity_load_factor * np.maximum(0.0, load_arr - 1.0))

    def _predicted_planner_rate(self, i: int, j: int, nominal_load: int, horizon: int, use_estimate: bool = True) -> float:
        future_pos = self._predict_user_position(i, horizon)
        future_dist = self._predict_disturbance(j, horizon, use_estimate=use_estimate)
        snr = self._planner_snr_for_state(future_pos, np.array([future_dist]))[0, j]
        return float(self._planner_rate_from_snr(np.array([snr]), nominal_load)[0])

    def planner_rate_matrix(self, *, use_proxy_model: bool = True, horizon: int | None = None) -> np.ndarray:
        """Return the planner's predicted per-AP service-rate matrix for the current state.

        For each AP column, the balanced-slot quota used by stable-global is applied.
        With ``use_proxy_model=False`` the authoritative evaluator model is used, which
        provides an oracle reference for model-mismatch diagnostics.
        """
        cfg = self.cfg
        h = cfg.prediction_horizon if horizon is None else int(horizon)
        n, m = cfg.n_users, cfg.n_aps
        quotas = np.full(m, n // m, dtype=int)
        quotas[: n % m] += 1
        future_positions = np.stack([self._predict_user_position(i, h) for i in range(n)], axis=0)
        future_disturbances = np.array(
            [self._predict_disturbance(j, h, use_estimate=True) for j in range(m)],
            dtype=float,
        )
        if use_proxy_model:
            future_snr = self._planner_snr_for_state(future_positions, future_disturbances)
            rate_for_quota = {
                int(q): self._planner_rate_from_snr(future_snr, int(q))
                for q in np.unique(quotas)
            }
        else:
            future_snr = self._snr_for_state(future_positions, future_disturbances)
            rate_for_quota = {
                int(q): self._rate_from_snr(future_snr, int(q))
                for q in np.unique(quotas)
            }
        out = np.zeros((n, m), dtype=float)
        for j in range(m):
            out[:, j] = rate_for_quota[int(quotas[j])][:, j]
        return out

    def _global_cost_matrix(
        self,
        demand: np.ndarray,
        *,
        switch_weight: float | None = None,
        use_proxy_model: bool = True,
    ) -> tuple[np.ndarray, np.ndarray]:
        cfg = self.cfg
        n, m = cfg.n_users, cfg.n_aps
        quotas = np.full(m, n // m, dtype=int)
        quotas[: n % m] += 1
        slots = np.concatenate([np.repeat(j, quotas[j]) for j in range(m)])
        risk = self._risk_vector(use_estimate=True)
        cost = np.zeros((n, n), dtype=float)
        switch_mult = cfg.global_switch_weight if switch_weight is None else float(switch_weight)
        future_positions = np.stack([self._predict_user_position(i, cfg.prediction_horizon) for i in range(n)], axis=0)
        future_disturbances = np.array(
            [self._predict_disturbance(j, cfg.prediction_horizon, use_estimate=True) for j in range(m)],
            dtype=float,
        )
        if use_proxy_model:
            future_snr = self._planner_snr_for_state(future_positions, future_disturbances)
            all_rates_by_quota = {
                int(q): self._planner_rate_from_snr(future_snr, int(q)) for q in np.unique(quotas)
            }
        else:
            future_snr = self._snr_for_state(future_positions, future_disturbances)
            all_rates_by_quota = {
                int(q): self._rate_from_snr(future_snr, int(q)) for q in np.unique(quotas)
            }

        for i in range(n):
            demand_i = float(demand[i])
            speed_ratio = float(np.linalg.norm(self.user_vel[i]) / max(cfg.max_speed, 1e-9))
            for s, j in enumerate(slots):
                q = int(quotas[int(j)])
                future_rate = float(all_rates_by_quota[q][i, int(j)])
                served_ratio = min(demand_i, future_rate) / max(demand_i, 1e-9)
                shortfall = max(0.0, demand_i - future_rate) / max(demand_i, 1e-9)
                switch_pen = switch_mult * cfg.handover_cost if int(j) != int(self.user_assoc[i]) else 0.0
                mobility_pen = cfg.global_mobility_weight * speed_ratio * float(
                    np.linalg.norm(future_positions[i] - self.ap_pos[int(j)]) / max(cfg.grid_size, 1e-9)
                )
                cost[i, s] = (
                    -cfg.global_served_weight * served_ratio
                    + cfg.global_shortfall_weight * shortfall
                    + cfg.global_risk_weight * float(risk[int(j)])
                    + mobility_pen
                    + switch_pen
                )
        return cost, slots

    def _stable_global_assoc(
        self,
        demand: np.ndarray,
        *,
        switch_weight: float | None = None,
        use_proxy_model: bool = True,
    ) -> np.ndarray:
        cost, slots = self._global_cost_matrix(
            demand, switch_weight=switch_weight, use_proxy_model=use_proxy_model
        )
        _, col_ind = linear_sum_assignment(cost)
        return slots[col_ind].astype(int)

    def _state_key(self, user_idx: int, assoc: np.ndarray) -> tuple[int, int, int, int, int]:
        cfg = self.cfg
        risk = float(np.mean(self._risk_vector(True)))
        mobility = float(np.mean(np.linalg.norm(self.user_vel, axis=1)) / max(cfg.max_speed, 1e-9))
        load = np.bincount(assoc, minlength=cfg.n_aps)
        load_ratio = float(load[int(self.user_assoc[user_idx])] / max(1, cfg.n_users))
        demand = float(self.user_demand[user_idx])
        demand_bin = int(np.clip(np.floor((demand - 1.0) / 6.0 * cfg.q_state_bins), 0, cfg.q_state_bins - 1))
        risk_bin = int(np.clip(np.floor(risk / (1.8 + 0.4 * cfg.disturbance_sigma)), 0, cfg.q_state_bins - 1))
        mobility_bin = int(np.clip(np.floor(mobility * cfg.q_state_bins), 0, cfg.q_state_bins - 1))
        load_bin = int(np.clip(np.floor(load_ratio * cfg.q_state_bins), 0, cfg.q_state_bins - 1))
        current_ap = int(self.user_assoc[user_idx])
        return risk_bin, mobility_bin, load_bin, demand_bin, current_ap

    def _reward(self, throughput: np.ndarray, demand: np.ndarray, new_assoc: np.ndarray) -> np.ndarray:
        switch_pen = (new_assoc != self.user_assoc).astype(float) * self.cfg.handover_cost
        shortage = np.maximum(0.0, demand - throughput) / np.maximum(demand, 1e-9)
        return throughput / np.maximum(demand, 1e-9) - 0.75 * shortage - 0.12 * switch_pen

    def choose_assoc(self, policy: PolicyName, demand: np.ndarray) -> np.ndarray:
        snr = self.link_score()
        n_users, n_aps = snr.shape
        assoc = self.user_assoc.copy()

        if policy == "rssi":
            return np.argmax(snr, axis=1)

        if policy == "hysteresis":
            best = np.argmax(snr, axis=1)
            for i in range(n_users):
                if best[i] != assoc[i] and snr[i, best[i]] > snr[i, assoc[i]] + self.cfg.hysteresis_db:
                    assoc[i] = best[i]
            return assoc

        if policy == "ttt_handover":
            best = np.argmax(snr, axis=1)
            for i in range(n_users):
                if best[i] == assoc[i]:
                    self.ttt_counter[i] = 0
                    self.ttt_target[i] = best[i]
                    continue
                if snr[i, best[i]] > snr[i, assoc[i]] + self.cfg.hysteresis_db:
                    if self.ttt_target[i] == best[i]:
                        self.ttt_counter[i] += 1
                    else:
                        self.ttt_target[i] = best[i]
                        self.ttt_counter[i] = 1
                    if self.ttt_counter[i] >= self.cfg.ttt_trigger_steps:
                        assoc[i] = best[i]
                        self.ttt_counter[i] = 0
                else:
                    self.ttt_counter[i] = 0
                    self.ttt_target[i] = assoc[i]
            return assoc

        if policy == "load_aware":
            counts = np.zeros(n_aps, dtype=int)
            for i in range(n_users):
                scores = np.array([self._rate_from_snr(np.array([snr[i, j]]), counts[j])[0] for j in range(n_aps)])
                j = int(np.argmax(scores))
                assoc[i] = j
                counts[j] += 1
            return assoc

        if policy in {"darc_no_obs", "darc", "robust_darc", "shield_darc"}:
            counts = np.zeros(n_aps, dtype=int)
            use_estimate = policy != "darc_no_obs"
            robust = policy in {"robust_darc", "shield_darc"}
            safe = False
            if policy == "shield_darc":
                risk = float(np.mean(self._risk_vector(True)))
                safe = risk > (0.56 * self.cfg.disturbance_sigma + self.cfg.regime_risk_offset)
            for i in range(n_users):
                utilities = np.array([
                    self._utility(i, j, counts, float(demand[i]), use_estimate=use_estimate, robust=robust, safe=safe)
                    for j in range(n_aps)
                ])
                j = int(np.argmax(utilities))
                assoc[i] = j
                counts[j] += 1
            return assoc

        if policy == "stable_global":
            return self._stable_global_assoc(demand, switch_weight=None, use_proxy_model=True)

        if policy == "stable_global_no_switch":
            return self._stable_global_assoc(demand, switch_weight=0.0)

        if policy == "stable_global_oracle":
            return self._stable_global_assoc(demand, switch_weight=None, use_proxy_model=False)

        if policy == "regime_orchestrator":
            return self.choose_assoc(self._select_regime_mode(), demand)

        if policy == "q_learning":
            epsilon = max(self.cfg.q_learning_epsilon_min, self.cfg.q_learning_epsilon * (self.cfg.q_learning_epsilon_decay ** self.trace_step))
            actions = np.zeros(n_users, dtype=int)
            for i in range(n_users):
                state = self._state_key(i, assoc)
                q = self.q_tables[i].setdefault(state, np.zeros(n_aps, dtype=float))
                if self.rng.random() < epsilon:
                    actions[i] = int(self.rng.integers(n_aps))
                else:
                    actions[i] = int(np.argmax(q))
            next_assoc = actions.copy()
            throughput, _, _, _ = self.evaluate_assignments(next_assoc, demand)
            reward = self._reward(throughput, demand, next_assoc)
            for i in range(n_users):
                old_state = self._state_key(i, assoc)
                next_state = self._state_key(i, next_assoc)
                q = self.q_tables[i].setdefault(old_state, np.zeros(n_aps, dtype=float))
                next_q = self.q_tables[i].setdefault(next_state, np.zeros(n_aps, dtype=float))
                a = actions[i]
                q[a] += self.cfg.q_learning_alpha * (reward[i] + self.cfg.q_learning_gamma * np.max(next_q) - q[a])
            return next_assoc

        raise ValueError(f"Unknown policy: {policy}")

    def run(self, policy: PolicyName = "darc", steps: int | None = None):
        cfg = self.cfg
        steps = int(steps or cfg.steps)
        metrics: Dict[str, Any] = {
            "throughput": [],
            "outage_rate": [],
            "served_demand_fraction": [],
            "mean_satisfaction": [],
            "p05_satisfaction": [],
            "mean_shortfall_fraction": [],
            "p05_throughput": [],
            "median_throughput": [],
            "jain": [],
            "handover_rate": [],
            "latency_proxy": [],
            "mean_load_cv": [],
            "disturbance_volatility": [],
            "shield_mode": [],
            "shock_index": [],
            "regime_mode": [],
            "disturbance": [],
            "disturbance_est": [],
            "disturbance_prev": [],
            "global_burst": [],
            "user_speed": [],
            "user_vel": [],
            "demand_hist": [],
            "load_ratio": [],
            "reward_mean": [],
        }

        user_thr_hist: list[np.ndarray] = []
        user_assoc_hist: list[np.ndarray] = []
        positions: list[np.ndarray] = []
        handovers = 0
        pingpong = 0

        for t in range(steps):
            self.trace_step = t
            self._prediction_cache.clear()
            if self.trace_data is not None:
                self._load_trace_step(t)
                self._observe_trace_disturbance(t)
            else:
                self._step_synthetic_environment()
                self.trace_step = t

            demand = self.demand_profile(t)
            shock_index = float(np.mean(np.abs(self.disturbance_est) + 0.7 * self.disturbance_volatility))
            selected_policy = self._select_regime_mode() if policy == "regime_orchestrator" else policy
            new_assoc = self.choose_assoc(selected_policy, demand)
            previous = self.user_assoc.copy()
            handovers += int(np.sum(new_assoc != previous))
            if len(user_assoc_hist) >= 2:
                prev_prev = user_assoc_hist[-2]
                pingpong += int(np.sum((prev_prev == new_assoc) & (previous != new_assoc) & (new_assoc != previous)))

            self.prev_assoc = previous
            self.user_assoc = new_assoc
            throughput, outage, _, counts = self.evaluate_assignments(new_assoc, demand)

            shortage_frac = np.maximum(0.0, demand - throughput) / np.maximum(demand, 1e-9)
            satisfaction = np.minimum(throughput, demand) / np.maximum(demand, 1e-9)
            served_fraction = float(np.sum(np.minimum(throughput, demand)) / max(np.sum(demand), 1e-9))
            jain = float((throughput.sum() ** 2) / (cfg.n_users * np.sum(throughput ** 2) + 1e-12))
            load_mean = float(np.mean(counts))
            load_cv = float(np.std(counts) / max(load_mean, 1e-9))
            latency_proxy = float(1.0 + 8.0 * np.mean(shortage_frac) + 0.75 * load_cv)
            reward = self._reward(throughput, demand, new_assoc)

            user_thr_hist.append(throughput.copy())
            user_assoc_hist.append(new_assoc.copy())
            positions.append(self.user_pos.copy())
            metrics["throughput"].append(float(np.mean(throughput)))
            metrics["outage_rate"].append(float(np.mean(outage)))
            metrics["served_demand_fraction"].append(served_fraction)
            metrics["mean_satisfaction"].append(float(np.mean(satisfaction)))
            metrics["p05_satisfaction"].append(float(np.quantile(satisfaction, 0.05)))
            metrics["mean_shortfall_fraction"].append(float(np.mean(shortage_frac)))
            metrics["p05_throughput"].append(float(np.quantile(throughput, 0.05)))
            metrics["median_throughput"].append(float(np.median(throughput)))
            metrics["jain"].append(jain)
            metrics["handover_rate"].append(float(np.mean(new_assoc != previous)))
            metrics["latency_proxy"].append(latency_proxy)
            metrics["mean_load_cv"].append(load_cv)
            metrics["disturbance_volatility"].append(float(np.mean(self.disturbance_volatility)))
            metrics["shield_mode"].append(float(selected_policy == "shield_darc" and shock_index > (0.56 * cfg.disturbance_sigma + cfg.regime_risk_offset)))
            metrics["shock_index"].append(shock_index)
            metrics["regime_mode"].append(selected_policy)
            metrics["disturbance"].append(self.disturbance.copy())
            metrics["disturbance_est"].append(self.disturbance_est.copy())
            metrics["disturbance_prev"].append(self.disturbance_prev.copy())
            metrics["global_burst"].append(float(self.global_burst))
            metrics["user_speed"].append(np.linalg.norm(self.user_vel, axis=1).copy())
            metrics["user_vel"].append(self.user_vel.copy())
            metrics["demand_hist"].append(demand.copy())
            metrics["load_ratio"].append(counts / max(1, cfg.n_users))
            metrics["reward_mean"].append(float(np.mean(reward)))

        metrics["user_thr"] = np.asarray(user_thr_hist)
        metrics["user_assoc"] = np.asarray(user_assoc_hist)
        metrics["positions"] = np.asarray(positions)
        metrics["total_handovers"] = int(handovers)
        metrics["pingpong_events"] = int(pingpong)
        for key in [
            "throughput", "outage_rate", "served_demand_fraction", "mean_satisfaction", "p05_satisfaction", "mean_shortfall_fraction",
            "p05_throughput", "median_throughput", "jain", "handover_rate", "latency_proxy",
            "mean_load_cv", "disturbance_volatility", "shield_mode", "shock_index", "reward_mean",
        ]:
            metrics[f"mean_{key}"] = float(np.mean(metrics[key]))
        metrics["mean_global_burst"] = float(np.mean(np.abs(metrics["global_burst"])))
        modes = np.asarray(metrics["regime_mode"], dtype=object)
        metrics["regime_switches"] = int(np.sum(modes[1:] != modes[:-1])) if len(modes) > 1 else 0
        metrics["mean_regime_switches"] = float(metrics["regime_switches"] / max(1, steps))
        metrics["mean_mode_darc"] = float(np.mean(modes == "darc"))
        metrics["mean_mode_robust"] = float(np.mean(modes == "robust_darc"))
        metrics["mean_mode_shield"] = float(np.mean(modes == "shield_darc"))
        metrics["mean_handover_rate"] = float(np.mean(metrics["handover_rate"]))
        return metrics
